export const lawFirms = [
  {
    id: 1,
    name: "Alpha Law Firm",
    lawyers: [
      {
        id: 1,
        name: "John Doe",
        specialty: "Divorce Lawyer",
        availability: 8,
        cost: 100,
        appointments: [],
        firmId: 1,
      },
      {
        id: 2,
        name: "Emily Carter",
        specialty: "Property Dispute Lawyer",
        availability: 6,
        cost: 120,
        appointments: [],
        firmId: 1,
      },
      {
        id: 3,
        name: "Mark Smith",
        specialty: "Family Law Lawyer",
        availability: 7,
        cost: 110,
        appointments: [],
        firmId: 1,
      },
      {
        id: 4,
        name: "Sophia Johnson",
        specialty: "Business Lawyer",
        availability: 5,
        cost: 150,
        appointments: [],
        firmId: 1,
      },
      {
        id: 5,
        name: "Daniel Lee",
        specialty: "Criminal Lawyer",
        availability: 9,
        cost: 160,
        appointments: [],
        firmId: 1,
      },
      {
        id: 6,
        name: "Olivia Walker",
        specialty: "Personal Injury Lawyer",
        availability: 6,
        cost: 130,
        appointments: [],
        firmId: 1,
      },
      {
        id: 7,
        name: "James Brown",
        specialty: "Medical Malpractice Lawyer",
        availability: 8,
        cost: 170,
        appointments: [],
        firmId: 1,
      },
      {
        id: 8,
        name: "Liam Harris",
        specialty: "Immigration Lawyer",
        availability: 7,
        cost: 140,
        appointments: [],
        firmId: 1,
      },
      {
        id: 9,
        name: "Ava Clark",
        specialty: "Contract Law Lawyer",
        availability: 6,
        cost: 115,
        appointments: [],
        firmId: 1,
      },
      {
        id: 10,
        name: "Lucas Davis",
        specialty: "Employment Law Lawyer",
        availability: 8,
        cost: 125,
        appointments: [],
        firmId: 1,
      },
    ],
  },
  {
    id: 2,
    name: "Beta Legal Advisors",
    lawyers: [
      {
        id: 11,
        name: "Michael Brown",
        specialty: "Criminal Lawyer",
        availability: 7,
        cost: 150,
        appointments: [],
        firmId: 2,
      },
      {
        id: 12,
        name: "Sarah Wilson",
        specialty: "Bankruptcy Lawyer",
        availability: 6,
        cost: 135,
        appointments: [],
        firmId: 2,
      },
      {
        id: 13,
        name: "David Miller",
        specialty: "Intellectual Property Lawyer",
        availability: 9,
        cost: 180,
        appointments: [],
        firmId: 2,
      },
      {
        id: 14,
        name: "Isabella Martin",
        specialty: "Real Estate Lawyer",
        availability: 7,
        cost: 140,
        appointments: [],
        firmId: 2,
      },
      {
        id: 15,
        name: "Ethan Thomas",
        specialty: "Environmental Lawyer",
        availability: 8,
        cost: 160,
        appointments: [],
        firmId: 2,
      },
      {
        id: 16,
        name: "Mia Martinez",
        specialty: "Tax Lawyer",
        availability: 5,
        cost: 170,
        appointments: [],
        firmId: 2,
      },
      {
        id: 17,
        name: "Benjamin Garcia",
        specialty: "Employment Law Lawyer",
        availability: 6,
        cost: 125,
        appointments: [],
        firmId: 2,
      },
      {
        id: 18,
        name: "Charlotte Allen",
        specialty: "Commercial Litigation Lawyer",
        availability: 7,
        cost: 150,
        appointments: [],
        firmId: 2,
      },
      {
        id: 19,
        name: "Aiden Scott",
        specialty: "Mergers and Acquisitions Lawyer",
        availability: 6,
        cost: 175,
        appointments: [],
        firmId: 2,
      },
      {
        id: 20,
        name: "Amelia Young",
        specialty: "Family Law Lawyer",
        availability: 8,
        cost: 120,
        appointments: [],
        firmId: 2,
      },
    ],
  },
  {
    id: 3,
    name: "Gamma Legal Partners",
    lawyers: [
      {
        id: 21,
        name: "John Wilson",
        specialty: "Corporate Lawyer",
        availability: 8,
        cost: 155,
        appointments: [],
        firmId: 3,
      },
      {
        id: 22,
        name: "Emma Taylor",
        specialty: "Divorce Lawyer",
        availability: 7,
        cost: 125,
        appointments: [],
        firmId: 3,
      },
      {
        id: 23,
        name: "Daniel Harris",
        specialty: "Criminal Lawyer",
        availability: 6,
        cost: 145,
        appointments: [],
        firmId: 3,
      },
      {
        id: 24,
        name: "Ella Moore",
        specialty: "Real Estate Lawyer",
        availability: 9,
        cost: 140,
        appointments: [],
        firmId: 3,
      },
      {
        id: 25,
        name: "Lucas Green",
        specialty: "Insurance Lawyer",
        availability: 7,
        cost: 130,
        appointments: [],
        firmId: 3,
      },
      {
        id: 26,
        name: "Sophia Clark",
        specialty: "Intellectual Property Lawyer",
        availability: 8,
        cost: 170,
        appointments: [],
        firmId: 3,
      },
      {
        id: 27,
        name: "James Robinson",
        specialty: "Personal Injury Lawyer",
        availability: 6,
        cost: 135,
        appointments: [],
        firmId: 3,
      },
      {
        id: 28,
        name: "Aiden Wright",
        specialty: "Family Law Lawyer",
        availability: 7,
        cost: 150,
        appointments: [],
        firmId: 3,
      },
      {
        id: 29,
        name: "Grace Lewis",
        specialty: "Tax Lawyer",
        availability: 8,
        cost: 160,
        appointments: [],
        firmId: 3,
      },
      {
        id: 30,
        name: "Oliver Evans",
        specialty: "Bankruptcy Lawyer",
        availability: 6,
        cost: 125,
        appointments: [],
        firmId: 3,
      },
    ],
  },
  {
    id: 4,
    name: "Delta Law Group",
    lawyers: [
      {
        id: 31,
        name: "Robert Martinez",
        specialty: "Medical Malpractice Lawyer",
        availability: 8,
        cost: 180,
        appointments: [],
        firmId: 4,
      },
      {
        id: 32,
        name: "Zoe White",
        specialty: "Estate Planning Lawyer",
        availability: 6,
        cost: 140,
        appointments: [],
        firmId: 4,
      },
      {
        id: 33,
        name: "Jack Anderson",
        specialty: "Real Estate Lawyer",
        availability: 9,
        cost: 130,
        appointments: [],
        firmId: 4,
      },
      {
        id: 34,
        name: "Chloe Robinson",
        specialty: "Criminal Lawyer",
        availability: 7,
        cost: 150,
        appointments: [],
        firmId: 4,
      },
      {
        id: 35,
        name: "Isaac King",
        specialty: "Bankruptcy Lawyer",
        availability: 6,
        cost: 135,
        appointments: [],
        firmId: 4,
      },
      {
        id: 36,
        name: "Lily Thomas",
        specialty: "Family Law Lawyer",
        availability: 8,
        cost: 110,
        appointments: [],
        firmId: 4,
      },
      {
        id: 37,
        name: "Benjamin Scott",
        specialty: "Immigration Lawyer",
        availability: 6,
        cost: 120,
        appointments: [],
        firmId: 4,
      },
      {
        id: 38,
        name: "Megan Lee",
        specialty: "Personal Injury Lawyer",
        availability: 9,
        cost: 145,
        appointments: [],
        firmId: 4,
      },
      {
        id: 39,
        name: "Ethan Young",
        specialty: "Corporate Lawyer",
        availability: 7,
        cost: 170,
        appointments: [],
        firmId: 4,
      },
      {
        id: 40,
        name: "Luna Walker",
        specialty: "Contract Law Lawyer",
        availability: 8,
        cost: 160,
        appointments: [],
        firmId: 4,
      },
    ],
  },
  {
    id: 5,
    name: "Epsilon Legal Experts",
    lawyers: [
      {
        id: 41,
        name: "James Turner",
        specialty: "Contract Law Lawyer",
        availability: 8,
        cost: 120,
        appointments: [],
        firmId: 5,
      },
      {
        id: 42,
        name: "Sophia Adams",
        specialty: "Criminal Lawyer",
        availability: 7,
        cost: 140,
        appointments: [],
        firmId: 5,
      },
      {
        id: 43,
        name: "William Foster",
        specialty: "Intellectual Property Lawyer",
        availability: 6,
        cost: 150,
        appointments: [],
        firmId: 5,
      },
      {
        id: 44,
        name: "Olivia Carter",
        specialty: "Divorce Lawyer",
        availability: 9,
        cost: 130,
        appointments: [],
        firmId: 5,
      },
      {
        id: 45,
        name: "Mason Hill",
        specialty: "Real Estate Lawyer",
        availability: 8,
        cost: 160,
        appointments: [],
        firmId: 5,
      },
      {
        id: 46,
        name: "Isabella Jackson",
        specialty: "Employment Law Lawyer",
        availability: 7,
        cost: 125,
        appointments: [],
        firmId: 5,
      },
      {
        id: 47,
        name: "Liam Nelson",
        specialty: "Family Law Lawyer",
        availability: 6,
        cost: 140,
        appointments: [],
        firmId: 5,
      },
      {
        id: 48,
        name: "Charlotte Gonzalez",
        specialty: "Tax Lawyer",
        availability: 8,
        cost: 175,
        appointments: [],
        firmId: 5,
      },
      {
        id: 49,
        name: "Oliver Baker",
        specialty: "Business Lawyer",
        availability: 7,
        cost: 155,
        appointments: [],
        firmId: 5,
      },
      {
        id: 50,
        name: "Amelia Perez",
        specialty: "Medical Malpractice Lawyer",
        availability: 9,
        cost: 180,
        appointments: [],
        firmId: 5,
      },
    ],
  },
  {
    id: 6,
    name: "Zeta Legal Advisors",
    lawyers: [
      {
        id: 51,
        name: "Gabriel White",
        specialty: "Contract Law Lawyer",
        availability: 7,
        cost: 115,
        appointments: [],
        firmId: 6,
      },
      {
        id: 52,
        name: "Ella Walker",
        specialty: "Immigration Lawyer",
        availability: 6,
        cost: 125,
        appointments: [],
        firmId: 6,
      },
      {
        id: 53,
        name: "Ryan Carter",
        specialty: "Family Law Lawyer",
        availability: 8,
        cost: 150,
        appointments: [],
        firmId: 6,
      },
      {
        id: 54,
        name: "Avery Lewis",
        specialty: "Criminal Lawyer",
        availability: 9,
        cost: 140,
        appointments: [],
        firmId: 6,
      },
      {
        id: 55,
        name: "Isla Harris",
        specialty: "Personal Injury Lawyer",
        availability: 7,
        cost: 130,
        appointments: [],
        firmId: 6,
      },
      {
        id: 56,
        name: "Zachary Lee",
        specialty: "Estate Planning Lawyer",
        availability: 6,
        cost: 145,
        appointments: [],
        firmId: 6,
      },
      {
        id: 57,
        name: "Eliot King",
        specialty: "Insurance Lawyer",
        availability: 8,
        cost: 160,
        appointments: [],
        firmId: 6,
      },
      {
        id: 58,
        name: "Chloe Harris",
        specialty: "Real Estate Lawyer",
        availability: 6,
        cost: 125,
        appointments: [],
        firmId: 6,
      },
      {
        id: 59,
        name: "Benjamin Adams",
        specialty: "Bankruptcy Lawyer",
        availability: 8,
        cost: 135,
        appointments: [],
        firmId: 6,
      },
      {
        id: 60,
        name: "Lily Allen",
        specialty: "Corporate Lawyer",
        availability: 9,
        cost: 170,
        appointments: [],
        firmId: 6,
      },
    ],
  },
  {
    id: 7,
    name: "Eta Law Associates",
    lawyers: [
      {
        id: 61,
        name: "Samuel Thomas",
        specialty: "Criminal Lawyer",
        availability: 7,
        cost: 140,
        appointments: [],
        firmId: 7,
      },
      {
        id: 62,
        name: "Chloe Clark",
        specialty: "Corporate Lawyer",
        availability: 8,
        cost: 160,
        appointments: [],
        firmId: 7,
      },
      {
        id: 63,
        name: "Olivia Walker",
        specialty: "Divorce Lawyer",
        availability: 9,
        cost: 120,
        appointments: [],
        firmId: 7,
      },
      {
        id: 64,
        name: "Isaac Williams",
        specialty: "Real Estate Lawyer",
        availability: 6,
        cost: 140,
        appointments: [],
        firmId: 7,
      },
      {
        id: 65,
        name: "Lily Turner",
        specialty: "Family Law Lawyer",
        availability: 8,
        cost: 110,
        appointments: [],
        firmId: 7,
      },
      {
        id: 66,
        name: "Mason Thomas",
        specialty: "Bankruptcy Lawyer",
        availability: 7,
        cost: 125,
        appointments: [],
        firmId: 7,
      },
      {
        id: 67,
        name: "Grace Evans",
        specialty: "Business Lawyer",
        availability: 6,
        cost: 145,
        appointments: [],
        firmId: 7,
      },
      {
        id: 68,
        name: "Charlotte Lewis",
        specialty: "Intellectual Property Lawyer",
        availability: 7,
        cost: 150,
        appointments: [],
        firmId: 7,
      },
      {
        id: 69,
        name: "Aiden Wright",
        specialty: "Personal Injury Lawyer",
        availability: 9,
        cost: 135,
        appointments: [],
        firmId: 7,
      },
      {
        id: 70,
        name: "Ethan Davis",
        specialty: "Immigration Lawyer",
        availability: 6,
        cost: 120,
        appointments: [],
        firmId: 7,
      },
    ],
  },
  {
    id: 8,
    name: "Theta Legal Solutions",
    lawyers: [
      {
        id: 71,
        name: "Grace Walker",
        specialty: "Real Estate Lawyer",
        availability: 9,
        cost: 135,
        appointments: [],
        firmId: 8,
      },
      {
        id: 72,
        name: "James Smith",
        specialty: "Corporate Lawyer",
        availability: 7,
        cost: 150,
        appointments: [],
        firmId: 8,
      },
      {
        id: 73,
        name: "Sophia Brown",
        specialty: "Employment Law Lawyer",
        availability: 8,
        cost: 140,
        appointments: [],
        firmId: 8,
      },
      {
        id: 74,
        name: "Daniel White",
        specialty: "Tax Lawyer",
        availability: 6,
        cost: 145,
        appointments: [],
        firmId: 8,
      },
      {
        id: 75,
        name: "Evelyn Scott",
        specialty: "Mergers and Acquisitions Lawyer",
        availability: 8,
        cost: 160,
        appointments: [],
        firmId: 8,
      },
      {
        id: 76,
        name: "Oliver Clark",
        specialty: "Medical Malpractice Lawyer",
        availability: 7,
        cost: 175,
        appointments: [],
        firmId: 8,
      },
      {
        id: 77,
        name: "Emily Lewis",
        specialty: "Family Law Lawyer",
        availability: 9,
        cost: 120,
        appointments: [],
        firmId: 8,
      },
      {
        id: 78,
        name: "Mason Harris",
        specialty: "Insurance Lawyer",
        availability: 6,
        cost: 130,
        appointments: [],
        firmId: 8,
      },
      {
        id: 79,
        name: "Mia Thompson",
        specialty: "Personal Injury Lawyer",
        availability: 7,
        cost: 150,
        appointments: [],
        firmId: 8,
      },
      {
        id: 80,
        name: "William Green",
        specialty: "Business Lawyer",
        availability: 8,
        cost: 155,
        appointments: [],
        firmId: 8,
      },
    ],
  },
];
